package com.example.MaidsTest.Base.Enum;

public enum ESuccess {
    BOOK_ADDED_SUCCESSFULLY,
    BOOK_UPDATED_SUCCESSFULLY,
    BOOK_DELETED_SUCCESSFULLY,
    GET_BOOK_SUCCESSFULLY,
    GET_ALL_BOOK_SUCCESSFULLY,

    PATRON_ADDED_SUCCESSFULLY,
    PATRON_UPDATED_SUCCESSFULLY,
    PATRON_DELETED_SUCCESSFULLY,
    GET_PATRON_SUCCESSFULLY,
    GET_ALL_PATRON_SUCCESSFULLY,

    BOOK_BORROWED_SUCCESSFULLY,
    BOOK_RETURNED_SUCCESSFULLY,
    BORROWING_RECORD_DELETED_SUCCESSFULLY,
    GET_BORROWING_RECORD_SUCCESSFULLY,
    GET_ALL_BORROWING_RECORD_SUCCESSFULLY,
}
